### ISSUE TITLE
Error transforming tracking dataset : position undefined

### ISSUE THREAD

**Issue by benoitblanc** [PySport/kloppy#19]
Hello,

I tried to use transform method to update tracking dataset to new pitch dimensions but I ran into error because ball position from first frame is `None`.

Here is the Traceback : 
```
Traceback (most recent call last):
  File "/Users/benoitblanc/Documents/Workspace/kloppy/examples/datasets/metrica.py", line 36, in <module>
    main()
  File "/Users/benoitblanc/Documents/Workspace/kloppy/examples/datasets/metrica.py", line 29, in main
    to_pitch_dimensions=[(-5500, 5500), (-3300, 3300)]
  File "/Users/benoitblanc/Documents/Workspace/kloppy/kloppy/helpers.py", line 80, in transform
    to_pitch_dimensions=to_pitch_dimensions
  File "/Users/benoitblanc/Documents/Workspace/kloppy/kloppy/domain/services/transformers/__init__.py", line 132, in transform_dataset
    frames = list(map(transformer.transform_frame, dataset.records))
  File "/Users/benoitblanc/Documents/Workspace/kloppy/kloppy/domain/services/transformers/__init__.py", line 76, in transform_frame
    ball_position=self.transform_point(frame.ball_position, flip),
  File "/Users/benoitblanc/Documents/Workspace/kloppy/kloppy/domain/services/transformers/__init__.py", line 29, in transform_point
    x_base = self._from_pitch_dimensions.x_dim.to_base(point.x)
AttributeError: 'NoneType' object has no attribute 'x'
```

This is an easy problem that I can solve for my first contribution 😄

**Comment by koenvo** [comment]
Thanks @benoitblanc !! Great catch
